name: ${project.artifactId}
main: work.xeltica.craft.core.XCorePlugin
version: ${project.version}
api-version: 1.16
softdepend:
  - Vault
commands:
  omikuji:
    description: おみくじを引きます。マイクラ内で1日に1回まで引けて、100クローバーかかります。
    usage: /omikuji
  respawn:
    description: メインワールドの初期スポーンに戻ります。
    usage: /respawn
  pvp:
    description: 現在のワールドのPvP設定を変更します。
    usage: /pvp <on/off>
    permission: otanoshimi.command.pvp
  signedit:
    description: 看板の指定行を編集します。
    usage: /signedit <行番号> <テキスト>
    permission: otanoshimi.command.signedit
  givetravelticket:
    description: トラベルチケットを授与します。
    usage: /givetravelticket <playerName> [type=NORMAL] [amount=1]
    permission: otanoshimi.command.givetravelticket
  givecustomitem:
    description: XelticaMCオリジナルアイテムを授与します。
    usage: /givetravelticket <playerName> <xphone>
    permission: otanoshimi.command.givecustomitem
  report:
    description: 処罰GUIを表示します。
    usage: /report <playerName>
    permission: otanoshimi.command.report
  localtime:
    description: 現在いるワールドの時間を設定します。
    usage: /localtime <add|set|query> [day|night|noon|midnight|sunrise|sunset|(数値)]
    permission: otanoshimi.command.localtime
  boat:
    description: ボートを召喚します。
    usage: /boat
    permission: otanoshimi.command.boat
  cart:
    description: トロッコを召喚します。
    usage: /cart
    permission: otanoshimi.command.cart
  promo:
    description: 市民への昇格方法を確認します。
    usage: /promo
  cat:
    description: CATモードの有効/無効を切り替えるか、現在のモードを取得します。
    usage: /cat [on/off]
    permission: otanoshimi.command.cat
  hub:
    aliases: [ hub ]
    description: ロビーに移動します。
    usage: /hub help
  xtp:
    aliases: [ xteleport ]
    description: 保存された過去位置を用いてテレポートします。
    usage: /xtp <world> [player]
    permission: otanoshimi.command.xtp
  __core_gui_event__:
    description: "?"
    usage: "?"
  debug:
    description: デバッグ
    usage: /debug
    permission: otanoshimi.command.debug
permissions:
  otanoshimi.command.pvp:
    default: op
  otanoshimi.command.givetravelticket:
    default: op
  otanoshimi.command.givecustomitem:
    default: op
  otanoshimi.command.signedit:
    default: op
  otanoshimi.command.report:
    default: op
  otanoshimi.command.localtime:
    default: op
  otanoshimi.command.boat:
    default: op
  otanoshimi.command.cart:
    default: op
  otanoshimi.citizen:
    default: op
  otanoshimi.staff:
    default: op
  otanoshimi.command.cat:
    default: true
  hub.teleport.sandbox:
    default: op
  hub.teleport.art:
    default: op
  hub.teleport.nightmare:
    default: op
  hub.gatekeeper.citizen:
    default: op
  hub.gatekeeper.staff:
    default: op
  otanoshimi.command.debug:
    default: op
  otanoshimi.command.xtp:
    default: op
  otanoshimi.command.xtp.other:
    default: op